---
== Application web

Implémenter la base de donnée, puis l'exporter et le ranger dans le dossier assets
Tu as modifié ton fichier /etc/hosts pour ajouter une entrée qui associe healthnorth.local à ton adresse locale 127.0.0.1.

Tu as créé un dossier projet contenant un fichier index.php qui sert de point d’entrée à ton application web.

Tu as lancé un serveur PHP intégré en lui demandant d’écouter sur healthnorth.local:8000. avec la commande php -S healthnorth.local:8000

couleur css 06a2ad

Résultat : tu peux maintenant accéder à ton application via ton navigateur en tapant http://healthnorth.local:8000

*TO DO*
faire un logo 
faire les mockup sur figma j'ai trooop la flemme pour l'instant
raccourcir le footer bcp trop gros mais je veux garder le mail pour ajt nous contacter 
bien mettre les lien des login et tous dans les href


apres avoir importer mes templates j'ai séparer mon header et mon footer
je les inclus avec include ou require en fonction de ce que je recherche ici je veux qu'il soit charger tout le tmeps donc require once

Je creer ensuite ma page de login, je prend donc mes template j'incul mon header et mon footer et je veille bien a ajouter le name "emai" dans l'input sinon ca ne serapas pris en compte dans la requête. Je veille aussi a bien être en post pour plus de sécuriter.

script sql ma star oublie pas de le mettre dans ton portfolio 
CREATE TABLE Patients (
    id_patient INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    num_secu VARCHAR(20),
    email VARCHAR(150),
    mdp VARCHAR(255)
);


CREATE TABLE Medecins (
    id_medecin INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    mdp VARCHAR(255),
    specialite VARCHAR(100)
);


CREATE TABLE Secretaires (
    id_secretaire INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    email VARCHAR(150),
    telephone VARCHAR(20),
    mdp VARCHAR(255)
);


CREATE TABLE Laboratoires (
    id_labo INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(150),
    adresse VARCHAR(255),
    telephone VARCHAR(20),
    email VARCHAR(150)
);


CREATE TABLE RendezVous (
    id_rdv INT AUTO_INCREMENT PRIMARY KEY,
    date_rdv DATE NOT NULL,
    heure TIME NOT NULL,
    specialite VARCHAR(100),
    statut VARCHAR(50),
    prix DECIMAL(10,2),

    id_patient INT,
    id_medecin INT,
    id_secretaire INT,

    FOREIGN KEY (id_patient) REFERENCES Patients(id_patient),
    FOREIGN KEY (id_medecin) REFERENCES Medecins(id_medecin),
    FOREIGN KEY (id_secretaire) REFERENCES Secretaires(id_secretaire)
);


CREATE TABLE Ordonnances (
    id_ordonnance INT AUTO_INCREMENT PRIMARY KEY,
    date_ordonnance DATE NOT NULL,
    type VARCHAR(100),
    contenu TEXT,

    id_patient INT,
    id_medecin INT,

    FOREIGN KEY (id_patient) REFERENCES Patients(id_patient),
    FOREIGN KEY (id_medecin) REFERENCES Medecins(id_medecin)
);


CREATE TABLE Examens (
    id_examen INT AUTO_INCREMENT PRIMARY KEY,
    type_examen VARCHAR(150),
    date_examen DATE,
    resultat TEXT,

    id_patient INT,
    id_labo INT,
    id_medecin INT,

    FOREIGN KEY (id_patient) REFERENCES Patients(id_patient),
    FOREIGN KEY (id_labo) REFERENCES Laboratoires(id_labo),
    FOREIGN KEY (id_medecin) REFERENCES Medecins(id_medecin)
);
# Fonctionnalité : Connexion / Authentification

## Objectif
Permettre aux utilisateurs (patients, médecins, secrétaires) d'accéder à leur espace sécurisé.

## Description
Formulaire de connexion + vérification du mot de passe + gestion des rôles.

## Pages concernées
- login.php
- verif_login.php
- dashboard_patient.php
- dashboard_medecin.php
- dashboard_secretaire.php

## Sécurité
- Hash des mots de passe
- Sessions
- Vérification des rôles
- Requêtes préparées PDO

Tu as créé la structure de ton projet en mode MVC
Tu as mis en place un dossier app et tu as commencé à organiser ton backend proprement :

app/Controllers → pour la logique (login, actions, redirections)

app/Models → pour les classes qui parlent à la base de données

app/Database → pour ta future classe Database.php

templates/ → pour tes vues (HTML)

assets/ → pour tes images, CSS, JS

public/index.php → point d’entrée de ton application

la class controller c'est par la que ca passer toute les routes